platform :ios, '16.0'
use_frameworks! :linkage => :static
use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

prepare_react_native_project!

$RNFirebaseAsStaticFramework = true

target 'ClickSolverPartner' do
  config = use_native_modules!

  use_react_native!(
    :path             => config[:reactNativePath],
    :app_path         => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled   => false,
    :fabric_enabled   => false,
    :new_arch_enabled => false
  )

  # Permissions
  setup_permissions(%w[
    LocationWhenInUse
    LocationAlways
    Notifications
    Contacts
    PhotoLibrary
    Camera
  ])

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'RNCPushNotificationIOS',   :path => '../node_modules/@react-native-community/push-notification-ios'

  target 'ClickSolverPartnerTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])

    # Add the include for char_traits_uc.h to ALL targets
    installer.pods_project.targets.each do |tgt|
      tgt.build_configurations.each do |cfg|
        cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        cfg.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        cfg.build_settings['CLANG_CXX_LIBRARY_STANDARD'] = 'libc++'

        # 🔥 include char_traits_uc.h globally
        traits = File.join(__dir__, 'char_traits_uc.h')
        flags = cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
        flags += " -include \"#{traits}\" -D_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_STRING_VIEW"
        cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] = flags

        # For simulator arm64 issues
        if tgt.name == 'Flipper'
          cfg.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
      end
    end

    # ✅ APPLY SAME TO react-jsi, react-jsinspector explicitly
    %w[React-jsi React-jsinspector].each do |target_name|
      installer.pods_project.targets.each do |tgt|
        next unless tgt.name == target_name
        tgt.build_configurations.each do |cfg|
          traits = File.join(__dir__, 'char_traits_uc.h')
          flags = cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
          flags += " -include \"#{traits}\" -D_LIBCPP_ABI_USE_WRAP_ITER_IN_STD_STRING_VIEW"
          cfg.build_settings['OTHER_CPLUSPLUSFLAGS'] = flags
        end
      end
    end
  end
end
