# Define podspec sources
source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup' # Correct react-native-permissions setup

prepare_react_native_project!

use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'partnermobileapp' do
  config = use_native_modules!

  # Disable Hermes engine
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false, # Hermes disabled
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Setup react-native-permissions
  setup_permissions([
    'LocationWhenInUse',
    'LocationAlways',
    'Notifications',
    'Contacts'
  ])

  # Push Notifications
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  # Optional: Background Fetch (Required for Background Geolocation)
  # pod 'react-native-background-fetch', :path => '../node_modules/react-native-background-fetch'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Minimum iOS version
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'

        # Exclude arm64 architecture for Flipper on iOS Simulator
        if target.name == 'Flipper'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
      end
    end

    # Workaround: Fix for Firebase static framework issues
    installer.pods_project.targets.each do |target|
      if target.name.start_with?('Firebase')
        target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end
    end
  end
end
